plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.1'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.4'
}

import org.gradle.internal.os.OperatingSystem

def isCi = System.getenv('CI') != null

ext {
    if (project.hasProperty('hytale_home')) {
        hytale_home = project.findProperty('hytale_home')
    }
    else if (isCi) {
        hytale_home = "${project.buildDir}/tmp/hytale-dummy"
    }
    else {
        def os = OperatingSystem.current()
        if (os.isWindows()) {
            hytale_home = "${System.getProperty("user.home")}/AppData/Roaming/Hytale"
        }
        else if (os.isMacOsX()) {
            hytale_home = "${System.getProperty("user.home")}/Library/Application Support/Hytale"
        }
        else if (os.isLinux()) {
            hytale_home = "${System.getProperty("user.home")}/.var/app/com.hypixel.HytaleLauncher/data/Hytale"
            if (!file(hytale_home).exists()) {
                hytale_home = "${System.getProperty("user.home")}/.local/share/Hytale"
            }
        }
    }
}

if (!isCi) {
    if (!project.hasProperty('hytale_home')) {
        throw new GradleException('Your Hytale install could not be detected automatically. If you are on an unsupported platform or using a custom install location, please define the install location using the hytale_home property.');
    }
    else if (!file(project.findProperty('hytale_home')).exists()) {
        throw new GradleException("Failed to find Hytale at the expected location. Please make sure you have installed the game. The expected location can be changed using the hytale_home property. Currently looking in ${project.findProperty('hytale_home')}")
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}

repositories {
    mavenCentral()

    maven {
        name = "hytale-release"
        url = uri("https://maven.hytale.com/release")
    }
    maven {
        name = "hytale-pre-release"
        url = uri("https://maven.hytale.com/pre-release")
    }
}

configurations {
    implementation.extendsFrom shadow
}

dependencies {
    implementation("com.hypixel.hytale:Server:2026.01.28-87d03be09")
    implementation 'io.netty:netty-all:4.2.10.Final'

    shadow 'org.mapdb:mapdb:3.1.0'
    shadow 'org.sejda.imageio:webp-imageio:0.1.6'
}

def serverRunDir = file("$projectDir/run")
if (!serverRunDir.exists()) {
    serverRunDir.mkdirs()
}

shadowJar {
    archiveClassifier.set('')

    relocate 'org.slf4j', 'fr.boul2gom.voxelatlas.libs.slf4j'
    relocate 'org.sejda', 'fr.boul2gom.voxelatlas.libs.sejda'

    configurations = [project.configurations.shadow]

    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'

    mergeServiceFiles()
}

tasks.named('jar') {
    dependsOn shadowJar
    enabled = false
}

tasks.named('build') {
    dependsOn shadowJar
}

tasks.register('updatePluginManifest') {
    def manifestFile = file('src/main/resources/manifest.json')
    doLast {
        if (!manifestFile.exists()) {
            throw new GradleException("Could not find manifest.json at ${manifestFile.path}!")
        }
        def manifestJson = new groovy.json.JsonSlurper().parseText(manifestFile.text)
        manifestJson.Version = version
        manifestJson.IncludesAssetPack = includes_pack.toBoolean()
        manifestFile.text = groovy.json.JsonOutput.prettyPrint(groovy.json.JsonOutput.toJson(manifestJson))
    }
}

tasks.named('processResources') {
    dependsOn 'updatePluginManifest'
}

def createServerRunArguments(String srcDir) {
    def parameters = '--bind 127.0.0.1:25565 --allow-op --disable-sentry --assets="' + "${hytale_home}/install/$patchline/package/game/latest/Assets.zip" + '"'
    def modPaths = []
    if (includes_pack.toBoolean()) {
        modPaths << srcDir
    }
    if (load_user_mods.toBoolean()) {
        modPaths << "${hytale_home}/UserData/Mods"
    }
    if (!modPaths.isEmpty()) {
        parameters += ' --mods="' + modPaths.join(',') + '"'
    }
    return parameters
}

idea.project.settings.runConfigurations {
    'HytaleServer'(org.jetbrains.gradle.ext.Application) {
        mainClass = 'com.hypixel.hytale.Main'
        moduleName = project.idea.module.name + '.main'
        programParameters = createServerRunArguments(sourceSets.main.java.srcDirs.first().parentFile.absolutePath)
        workingDirectory = serverRunDir.absolutePath
    }
}
